# Generated by Django 2.0.1 on 2018-01-28 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='players',
            field=models.ManyToManyField(related_name='playing_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
